# Project: Movie
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main_movie.o
LINKOBJ  = main_movie.o
LIBS     = -L"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -pg
INCS     = -I"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = movie.exe
CXXFLAGS = $(CXXINCS) -m32 -pg #include <bits/stdc++.h>
CFLAGS   = $(INCS) -m32 -pg #include <bits/stdc++.h>
DEL      = C:\Program Files\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main_movie.o: main_movie.cpp
	$(CPP) -c main_movie.cpp -o main_movie.o $(CXXFLAGS)
